export const GENERATE_SUBMIT_NODE_BEGIN = 'GENERATE_SUBMIT_NODE_BEGIN';
export const GENERATE_SUBMIT_NODE_SUCCESS = 'GENERATE_SUBMIT_NODE_SUCCESS';
export const GENERATE_SUBMIT_NODE_FAILURE = 'GENERATE_SUBMIT_NODE_FAILURE';
export const GENERATE_SUBMIT_NODE_DISMISS_ERROR = 'GENERATE_SUBMIT_NODE_DISMISS_ERROR';
