export const GENERATE_SUBMIT_NODE_BEGIN = 'GENERATE_SUBMIT_NODE_BEGIN';
export const GENERATE_SUBMIT_NODE_SUCCESS = 'GENERATE_SUBMIT_NODE_SUCCESS';
export const GENERATE_SUBMIT_NODE_FAILURE = 'GENERATE_SUBMIT_NODE_FAILURE';
export const GENERATE_SUBMIT_NODE_DISMISS_ERROR = 'GENERATE_SUBMIT_NODE_DISMISS_ERROR';
export const GENERATE_SUBMIT_FRONT_BEGIN = 'GENERATE_SUBMIT_FRONT_BEGIN';
export const GENERATE_SUBMIT_FRONT_SUCCESS = 'GENERATE_SUBMIT_FRONT_SUCCESS';
export const GENERATE_SUBMIT_FRONT_FAILURE = 'GENERATE_SUBMIT_FRONT_FAILURE';
export const GENERATE_SUBMIT_FRONT_DISMISS_ERROR = 'GENERATE_SUBMIT_FRONT_DISMISS_ERROR';
