const initialState = {
  adminList:[],
  adminPage:1,
  adminSize:10,
  adminTotal:0,
  adminById:{},
  adminModalType:"create",
  adminModalVisible:false,
  currentAdmin:{},
  getAdminListPending: false,
  getAdminListError: null,
  submitAdminPending: false,
  submitAdminError: null,
  deleteAdminPending: false,
  deleteAdminError: null,
  deptList:[],
  deptPage:1,
  deptSize:10,
  deptTotal:0,
  deptById:{},
  deptModalType:"create",
  deptModalVisible:false,
  currentDept:{},
  getDeptListPending: false,
  getDeptListError: null,
  submitDeptPending: false,
  submitDeptError: null,
  deleteDeptPending: false,
  deleteDeptError: null,
  getAllDeptPending: false,
  getAllDeptError: null,
  deptTree:[],
  allDeptById:{}
};

export default initialState;
