export const COMMON_COLLAPSE_CHANGE = 'COMMON_COLLAPSE_CHANGE';
export const COMMON_SET_LOADING = 'COMMON_SET_LOADING';
export const COMMON_LOGOUT_SUCCESS = 'COMMON_LOGOUT_SUCCESS';
export const COMMON_CHANGE_ROLE_LIST = 'COMMON_CHANGE_ROLE_LIST';
